name: repro
version: 0.0.0.1
github: "tomasaschan/vscode-hls-repro"
license: MIT
author: "Tomas Aschan"
maintainer: "1550920+tomasaschan@users.noreply.github.com"
copyright: "2020 Tomas Aschan"

library:
  source-dirs: lib
  ghc-options:
    - -Wall
  dependencies:
    - base
    - containers
